# Site
title:              AlucardSama04 Blog
bio:                'Blog dă fansubăr'
description:        "Blogul meu."
logo:               https://i.postimg.cc/bJYndySQ/image.jpg
avatar:             https://i.imgur.com/p38SMdA.jpg
notFoundImage:      https://i.postimg.cc/85N1S4n5/d2n30qh-44d67dd6-50a8-4b6e-96ce-0b60a672c96b.png
locale:             en_US
url:                https://alucardsama04.github.io
author:             AlucardSama04

# Jekyll
permalink:          /p/:title/
paginate:           8
paginate_path:      /post/page:numn
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false


sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   alucardsama04
twitter:            AlucardSama04
github-url:         AlucardSama04


# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
